name: facilite

# Descrição do App
# Facilite+ é um aplicativo simples e eficiente para gerenciar seus empréstimos.
# Ideal para quem precisa de uma solução descomplicada para manter suas finanças em dia.

description: "Facilite+ é um aplicativo simples e eficiente para gerenciar seus empréstimos. Com ele, você pode registrar, acompanhar e organizar todas as suas transações de forma prática e intuitiva. Controle prazos, valores e pagamentos, tudo em um só lugar, com facilidade e rapidez. Ideal para quem precisa de uma solução descomplicada para manter suas finanças em dia."

# Configuração de Publicação
debugShowCheckedModeBanner: false
publish_to: 'none' # Impede a publicação acidental no pub.dev

# Versão do App
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Dependências de Interface
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  glassmorphism_widgets: ^0.2.2
  animate_do: ^3.3.4

  # Dependências para Gerenciamento de Estado e Banco de Dados
  provider: ^6.1.2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4

  # Dependências Utilitárias
  url_launcher: ^6.3.1
  intl: ^0.20.1
  mask_text_input_formatter: ^2.9.0
  flutter_multi_formatter: ^2.13.0
  bcrypt: ^1.1.3

  # Dependências para Gráficos e PDFs
  fl_chart: ^0.70.0
  pdf: ^3.11.1
  printing: ^5.13.4

  # Gerenciamento de Janelas para Desktop
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
